### ISSUE TITLE
Ellenfelek helyes elrendezése

### ISSUE THREAD

**Issue by langfalvidavid473** [langfalvidavid473/Tokfilkok#20]
**Probléma:** Nem mindegyik szörnynek van ugyanott a középpontja, ezért el vannak csúszva egymáshoz képest.
**Megoldás:** Be kell húzni az alábbi szörnyeket, hogy futtatásnál egy vonalban legyenek.
**Amik rossz helyen vannak:**
- Gomba
- Krumpli
- Banán
- Tök

**Comment by xrichard20** [comment]
Egységesítettem a középpontokat mindegyik ellenfélnél
