### ISSUE TITLE
További billentyűk használata

### ISSUE THREAD

**Issue by langfalvidavid473** [langfalvidavid473/Tokfilkok#27]
El kell dönteni, hogy melyik billentyűket lássuk el további funkciókkal.
- Támadás, kitérés stb.... (minden ami interakció)
_Egy gomb több funkciót is elláthat, csak nem egy ajtón belül_

**Comment by Spory01** [comment]
Ajtó választás(elágazás):
- bal/jobb nyíl
Teremben akciók:
- bal nyíl --- szörny megtámadása
- jobb nyíl --- menekülés
- E --- tárgyfelvétel
- előre nyíl --- tárgyfelvétel vagy harc után hogy haladhass tovább
- ESC --- kilépés
