### ISSUE TITLE
Név megjelenítése

### ISSUE THREAD

**Issue by langfalvidavid473** [langfalvidavid473/Tokfilkok#30]
Probléma: parancssor ki tudja írni az UTF-8 karaktereket, viszont string változóban nem lehet eltárolni, ezáltal a felhasználó által begépelt név hiányos lesz (ékezetes karakterek lemaradnak).
Ötlet 1: Keresni valami olyan könyvtárat, ami rendelkezik olyan bekérő függvénnyel, ami felismeri az ékezetes karaktereket is.
Ötlet 2: Írni egy függvényt, ami kicseréli az ékezetes karaktereket angol betűkre.

**Comment by Spory01** [comment]
Ez egy próbát megérhet:
https://stackoverflow.com/questions/32338496/what-is-the-difference-between-stdcout-and-stdwcout

Annyi a lényeg, hogy std::cout helyett std::wcout kell.
